[package]
name = "astroport-tokenfactory-tracker"
version = "1.0.0"
edition = "2021"

[features]
library = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
osmosis-std = "0.20.1"
cosmwasm-std = "1.1"
cosmwasm-schema = "1.1"
cw-storage-plus = "1.0"
thiserror = "1.0"
astroport = { path = "../../../packages/astroport", version = "3" }

[dev-dependencies]
cw-multi-test = "0.16.4"
serde_json = "1.0.96"
anyhow = "1"
derivative = "2.2"
itertools = "0.10"
