[package]
name = "astroport-tokenfactory-tracker"
version = "1.0.0"
edition = "2021"

[features]
library = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cw2.workspace = true
cosmwasm-std.workspace = true
cw-storage-plus.workspace = true
cosmwasm-schema.workspace = true
thiserror.workspace = true
astroport = { path = "../../../packages/astroport", version = "4" }

[dev-dependencies]
osmosis-std = "0.21"
osmosis-test-tube = "21.0.0"
test-tube = "0.3.0"
