[package]
name = "astroport-tokenfactory-tracker"
version = "1.0.0"
edition = "2021"

[features]
library = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cw2 = "1.1"
cosmwasm-std = "1.1"
cw-storage-plus = "1.0"
cosmwasm-schema = "1.1"
thiserror = "1.0"
astroport = { path = "../../../packages/astroport", version = "3" }
