[workspace]
resolver = "2"
members = [
    "packages/*",
    "contracts/factory",
    "contracts/pair",
    "contracts/pair_stable",
    "contracts/pair_concentrated",
    "contracts/pair_transmuter",
    #  "contracts/pair_concentrated_inj", TODO: rewrite OB liquidity deployment
    "contracts/pair_astro_xastro",
    "contracts/pair_xyk_sale_tax",
    "contracts/router",
    "contracts/token",
    "contracts/whitelist",
    #  "contracts/cw20_ics20", # contract is being deprecated
    "templates/*",
    "contracts/tokenomics/incentives",
    "contracts/tokenomics/maker",
    "contracts/tokenomics/staking",
    "contracts/tokenomics/vesting",
    "contracts/tokenomics/xastro_outpost_token",
    "contracts/tokenomics/xastro_token",
    "contracts/periphery/fee_granter",
    "contracts/periphery/native_coin_registry",
    "contracts/periphery/native-coin-wrapper",
    "contracts/periphery/oracle",
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
strip = true


[patch.'https://github.com/astroport-fi/hidden_astroport_core']
astroport = { path = "packages/astroport" }

[patch.'https://github.com/astroport-fi/astroport-core']
astroport = { path = "packages/astroport" }
