[package]
name = "astroport"
version = "3.13.0"
authors = ["Astroport"]
edition = "2021"
description = "Common Astroport types, queriers and other utils"
license = "Apache-2.0"
repository = "https://github.com/astroport-fi/astroport"
homepage = "https://astroport.fi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
injective = ["injective-math", "thiserror"]
sei = []

[dependencies]
cw20 = { version = "0.15" }
cosmwasm-std = { version = "1.1", features = ["cosmwasm_1_1", "stargate"]}
uint = "0.9"
cw-storage-plus = "0.15"
itertools = "0.10"
cosmwasm-schema = "1.1"
astroport-circular-buffer = { version = "0.2", path = "../circular_buffer" }
cw-utils = "1.0"
cw3 = "1.0"
cw-asset = "3.0.0"
prost = "0.11.5"
cosmos-sdk-proto = { version = "0.19.0", default-features = false }

# optional
injective-math = { version = "0.1", optional = true }
thiserror = { version = "1.0", optional = true }

[dev-dependencies]
test-case = "3.1.0"
