[package]
name = "astroport-incentives"
version = "1.0.0"
authors = ["Astroport"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
cosmwasm-std = "1.3"
cw-storage-plus = "0.15"
cosmwasm-schema = "1.4"
cw2 = "1"
cw20 = "1"
cw-utils = "1"
astroport = { path = "../../../packages/astroport" }
thiserror = "1"
itertools = "0.11"

[dev-dependencies]
cw-multi-test = { git = "https://github.com/astroport-fi/cw-multi-test", branch = "astroport_cozy_fork" }
anyhow = "1"
astroport-factory = { path = "../../factory" }
astroport-pair = { path = "../../pair" }
astroport-pair-stable = { path = "../../pair_stable" }
astroport-native-coin-registry = { path = "../../periphery/native_coin_registry" }
astroport-vesting = { path = "../vesting" }
cw20-base = "1"
proptest = "1.3"
