[package]
name = "astroport-test"
version = "0.1.0"
authors = ["Astroport"]
edition = "2021"
description = "Mock Astroport contracts used for integration testing"
license = "GPL-3.0-only"
repository = "https://github.com/astroport-fi/astroport-core"
homepage = "https://astroport.fi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
astroport = { path = "../astroport" }
cosmwasm-schema = "1.2.5"
cosmwasm-std = "1.2.5"
cw-multi-test = { package = "cw-multi-test", version = "1.0.0", features = ["cosmwasm_1_1"] }
serde = "1.0"
schemars = "0.8.1"
anyhow = "1.0"


