[package]
name = "astroport-maker"
version = "1.4.0"
authors = ["Astroport"]
edition = "2021"

exclude = [
    # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
    "contract.wasm",
    "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]


[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1.5"
cw2 = "1"
cw20 = "1"
cw-storage-plus = "0.15"
astroport = { path = "../../../packages/astroport", version = "3.12" }
thiserror = "1"
cosmwasm-schema = "1.5"
astro-satellite-package = { git = "https://github.com/astroport-fi/astroport_ibc", version = "1" }

[dev-dependencies]
cw20-base = "1"
astroport-factory = { path = "../../factory" }
astroport-pair = { path = "../../pair" }
cw-multi-test = "0.20"
astroport-pair-stable = { path = "../../pair_stable" }
astroport-governance = { git = "https://github.com/astroport-fi/hidden_astroport_governance", version = "1" }
astroport-escrow-fee-distributor = { git = "https://github.com/astroport-fi/hidden_astroport_governance", version = "1" }
astroport-native-coin-registry = { path = "../../periphery/native_coin_registry" }
