[package]
name = "astroport-maker"
version = "1.5.0"
authors = ["Astroport"]
edition = "2021"
description = "Astroport Maker contract"
license = "GPL-3.0-only"
repository = "https://github.com/astroport-fi/astroport"
homepage = "https://astroport.fi"

exclude = [
    # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
    "contract.wasm",
    "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]


[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std.workspace = true
cw2.workspace = true
cw20 = "1"
cw-storage-plus.workspace = true
astroport = { path = "../../../packages/astroport", version = "4" }
thiserror.workspace = true
cosmwasm-schema.workspace = true
astro-satellite-package = { git = "https://github.com/astroport-fi/astroport_ibc", version = "1" }

[dev-dependencies]
cw20-base = "1"
astroport-factory = { path = "../../factory" }
astroport-pair = { path = "../../pair" }
cw-multi-test = "1.0.0"
astroport-pair-stable = { path = "../../pair_stable" }
astroport-governance = { git = "https://github.com/astroport-fi/astroport-governance", version = "3", branch = "feat/astroport_governance_v3" }
astroport-native-coin-registry = { path = "../../periphery/native_coin_registry" }
