[package]
name = "astroport-staking"
version = "2.0.0"
authors = ["Astroport"]
edition = "2021"
license = "GPL-3"

exclude = [
    # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
    "contract.wasm",
    "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.5", features = ["cosmwasm_1_1"] }
cw-storage-plus = "1.2"
thiserror = "1"
cw2 = "1.1"
astroport = { path = "../../../packages/astroport", version = "3" }
cw-utils = "1"
osmosis-std = "0.21"

[dev-dependencies]
anyhow = "1"
itertools = "0.12"
cosmwasm-schema = "1.5"
cw-multi-test = { version = "0.20", features = ["cosmwasm_1_1"] }
astroport-tokenfactory-tracker = { path = "../../periphery/tokenfactory_tracker" }
