[package]
name = "astroport-staking"
version = "1.0.0"
authors = ["Terraform Labs, PTE."]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "0.15.0" }
cw-storage-plus = "0.7.0" 
schemars = "0.8.1"
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.24" }
cw2 = "0.7"
cw20 = "0.7"
terraswap = { path = "../../../packages/terraswap", default-features = false, version = "2.1.0"}

[dev-dependencies]
cosmwasm-schema = { version = "0.15.0" }
terraswap = {path = "../../../packages/terraswap"}
terraswap-token = {path = "../../terraswap_token"}
cw-multi-test = "0.7.0"
