[package]
name = "terraswap"
version = "1.2.0"
authors = ["Terraform Labs, PTE."]
edition = "2018"
description = "Common terraswap types"
license = "Apache-2.0"
repository = "https://github.com/terraswap/terraswap"
homepage = "https://terraswap.io"
documentation = "https://docs.terraswap.io"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.2" }
cosmwasm-storage = { version = "0.10.1" }
terra-cosmwasm = { version = "1.2.3" }
cosmwasm-std = { version = "0.10.1" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "0.10.1"

[profile.release]
overflow-checks = true
