[package]
name = "astroport-vesting"
version = "1.4.0"
authors = ["Astroport"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cw2 = "1.1"
cw20 = "0.15"
cosmwasm-std = "1.5"
cw-storage-plus = "0.15"
astroport = { path = "../../../packages/astroport", version = "3" }
thiserror = "1"
cw-utils = "1"
cosmwasm-schema = "1.5"

[dev-dependencies]
cw-multi-test = "0.20"
cw20-base = "0.15"
astro-token-converter = { path = "../../periphery/astro_converter", version = "1", features = ["library"] }
astroport-vesting_131 = { package = "astroport-vesting", version = "=1.3.1", features = ["library"] }

