[package]
name = "astroport-vesting"
version = "1.4.0"
authors = ["Astroport"]
edition = "2021"
description = "Astroport Vesting Contract holds tokens and releases them to the beneficiary over time."
license = "GPL-3.0-only"
repository = "https://github.com/astroport-fi/astroport"
homepage = "https://astroport.fi"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cw2 = "1.1"
cw20 = "0.15"
cosmwasm-std = "1.5"
cw-storage-plus = "0.15"
astroport = { path = "../../../packages/astroport", version = "3" }
thiserror = "1"
cw-utils = "1"
cosmwasm-schema = "1.5"

[dev-dependencies]
cw-multi-test = "1.0.0"
cw20-base = "0.15"
astro-token-converter = { path = "../../periphery/astro_converter", version = "1", features = ["library"] }
astroport-vesting_131 = { package = "astroport-vesting", version = "=1.3.1", features = ["library"] }

