[package]
name = "astroport-vesting"
version = "1.0.0"
authors = ["Terraform Labs, PTE."]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cw20 = { version = "0.7" }
cosmwasm-std = { version = "0.15.0" }
cw-storage-plus = {version = "0.7.0", features = ['iterator']}
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terraswap = { path = "../../../packages/terraswap", default-features = false, version = "2.1.0"}
thiserror = { version = "1.0.20" }

[dev-dependencies]
cosmwasm-schema = { version = "0.15.0", default-features = false  }
