[package]
name = "astroport-vesting"
version = "1.0.0"
authors = ["Terraform Labs, PTE."]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cw20 = { version = "0.6" }
cosmwasm-std = { version = "0.14.0" }
cosmwasm-storage = { version = "0.14.0" }
cw-storage-plus = {version = "0.6.0", features = ['iterator']}
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terraswap = { path = "../../../packages/terraswap", default-features = false, version = "2.1.0"}
thiserror = { version = "1.0.20" }

[dev-dependencies]
cosmwasm-schema = { version = "0.14.0", default-features = false  }
