name: Validate Artifacts
on:
  push:


jobs:
  validate-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Artifacts
        run: |
          $GITHUB_WORKSPACE/scripts/build_release.sh
      - uses: chrysanthos/simple-asset-size-reporter@1.0.0
        with:
          files: artifacts/
          with-same: 'true'